// Generated from artwork progress manifests by sync-site or sync-styles. Do not edit.
export const seriesEventIds = [
  "childrens-day",
  "double-ninth",
  "dragon-boat",
  "laba",
  "labour-day",
  "lantern-festival",
  "mid-autumn",
  "national-day",
  "new-year",
  "new-years-eve",
  "qingming-festival",
  "qixi",
  "spring-festival",
  "teachers-day",
  "term-bailu",
  "term-chunfen",
  "term-chushu",
  "term-dahan",
  "term-dashu",
  "term-daxue",
  "term-dongzhi",
  "term-guyu",
  "term-hanlu",
  "term-jingzhe",
  "term-lichun",
  "term-lidong",
  "term-liqiu",
  "term-lixia",
  "term-mangzhong",
  "term-qingming",
  "term-qiufen",
  "term-shuangjiang",
  "term-xiaohan",
  "term-xiaoman",
  "term-xiaoshu",
  "term-xiaoxue",
  "term-xiazhi",
  "term-yushui",
  "womens-day",
  "youth-day"
] as const;
export const seriesArtwork: Record<string, Record<string, string>> = {
  "childrens-day": {
    "minimal": "/assets/minimal/childrens-day-minimal-v1.webp",
    "character": "/assets/character/childrens-day-character-v1.webp",
    "anime": "/assets/anime/childrens-day-anime-v1.webp",
    "sweet": "/assets/sweet/childrens-day-sweet-v1.webp",
    "watercolor": "/assets/watercolor/childrens-day-watercolor-v1.webp",
    "papercut": "/assets/papercut/childrens-day-papercut-v1.webp",
    "clay": "/assets/clay/childrens-day-clay-v1.webp",
    "woodblock": "/assets/woodblock/childrens-day-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/childrens-day-embroidery-v1.webp"
  },
  "double-ninth": {
    "minimal": "/assets/minimal/double-ninth-minimal-v1.webp",
    "character": "/assets/character/double-ninth-character-v1.webp",
    "anime": "/assets/anime/double-ninth-anime-v1.webp",
    "sweet": "/assets/sweet/double-ninth-sweet-v1.webp",
    "watercolor": "/assets/watercolor/double-ninth-watercolor-v1.webp",
    "papercut": "/assets/papercut/double-ninth-papercut-v1.webp",
    "clay": "/assets/clay/double-ninth-clay-v1.webp",
    "woodblock": "/assets/woodblock/double-ninth-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/double-ninth-embroidery-v1.webp"
  },
  "dragon-boat": {
    "minimal": "/assets/minimal/dragon-boat-minimal-v1.webp",
    "character": "/assets/character/dragon-boat-character-v1.webp",
    "anime": "/assets/anime/dragon-boat-anime-v1.webp",
    "sweet": "/assets/sweet/dragon-boat-sweet-v1.webp",
    "watercolor": "/assets/watercolor/dragon-boat-watercolor-v1.webp",
    "papercut": "/assets/papercut/dragon-boat-papercut-v1.webp",
    "clay": "/assets/clay/dragon-boat-clay-v1.webp",
    "woodblock": "/assets/woodblock/dragon-boat-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/dragon-boat-embroidery-v1.webp"
  },
  "laba": {
    "minimal": "/assets/minimal/laba-minimal-v1.webp",
    "character": "/assets/character/laba-character-v1.webp",
    "anime": "/assets/anime/laba-anime-v1.webp",
    "sweet": "/assets/sweet/laba-sweet-v1.webp",
    "watercolor": "/assets/watercolor/laba-watercolor-v1.webp",
    "papercut": "/assets/papercut/laba-papercut-v1.webp",
    "clay": "/assets/clay/laba-clay-v1.webp",
    "woodblock": "/assets/woodblock/laba-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/laba-embroidery-v1.webp"
  },
  "labour-day": {
    "minimal": "/assets/minimal/labour-day-minimal-v1.webp",
    "character": "/assets/character/labour-day-character-v1.webp",
    "anime": "/assets/anime/labour-day-anime-v1.webp",
    "sweet": "/assets/sweet/labour-day-sweet-v1.webp",
    "watercolor": "/assets/watercolor/labour-day-watercolor-v1.webp",
    "papercut": "/assets/papercut/labour-day-papercut-v1.webp",
    "clay": "/assets/clay/labour-day-clay-v1.webp",
    "woodblock": "/assets/woodblock/labour-day-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/labour-day-embroidery-v1.webp"
  },
  "lantern-festival": {
    "minimal": "/assets/minimal/lantern-festival-minimal-v1.webp",
    "character": "/assets/character/lantern-festival-character-v1.webp",
    "anime": "/assets/anime/lantern-festival-anime-v1.webp",
    "sweet": "/assets/sweet/lantern-festival-sweet-v1.webp",
    "watercolor": "/assets/watercolor/lantern-festival-watercolor-v1.webp",
    "papercut": "/assets/papercut/lantern-festival-papercut-v1.webp",
    "clay": "/assets/clay/lantern-festival-clay-v1.webp",
    "woodblock": "/assets/woodblock/lantern-festival-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/lantern-festival-embroidery-v1.webp"
  },
  "mid-autumn": {
    "minimal": "/assets/minimal/mid-autumn-minimal-v1.webp",
    "character": "/assets/character/mid-autumn-character-v1.webp",
    "anime": "/assets/anime/mid-autumn-anime-v1.webp",
    "sweet": "/assets/sweet/mid-autumn-sweet-v1.webp",
    "watercolor": "/assets/watercolor/mid-autumn-watercolor-v1.webp",
    "papercut": "/assets/papercut/mid-autumn-papercut-v1.webp",
    "clay": "/assets/clay/mid-autumn-clay-v1.webp",
    "woodblock": "/assets/woodblock/mid-autumn-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/mid-autumn-embroidery-v1.webp"
  },
  "national-day": {
    "minimal": "/assets/minimal/national-day-minimal-v1.webp",
    "character": "/assets/character/national-day-character-v1.webp",
    "anime": "/assets/anime/national-day-anime-v1.webp",
    "sweet": "/assets/sweet/national-day-sweet-v1.webp",
    "watercolor": "/assets/watercolor/national-day-watercolor-v1.webp",
    "papercut": "/assets/papercut/national-day-papercut-v1.webp",
    "clay": "/assets/clay/national-day-clay-v1.webp",
    "woodblock": "/assets/woodblock/national-day-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/national-day-embroidery-v1.webp"
  },
  "new-year": {
    "minimal": "/assets/minimal/new-year-minimal-v1.webp",
    "character": "/assets/character/new-year-character-v1.webp",
    "anime": "/assets/anime/new-year-anime-v1.webp",
    "sweet": "/assets/sweet/new-year-sweet-v1.webp",
    "watercolor": "/assets/watercolor/new-year-watercolor-v1.webp",
    "papercut": "/assets/papercut/new-year-papercut-v1.webp",
    "clay": "/assets/clay/new-year-clay-v1.webp",
    "woodblock": "/assets/woodblock/new-year-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/new-year-embroidery-v1.webp"
  },
  "new-years-eve": {
    "minimal": "/assets/minimal/new-years-eve-minimal-v1.webp",
    "character": "/assets/character/new-years-eve-character-v1.webp",
    "anime": "/assets/anime/new-years-eve-anime-v1.webp",
    "sweet": "/assets/sweet/new-years-eve-sweet-v1.webp",
    "watercolor": "/assets/watercolor/new-years-eve-watercolor-v1.webp",
    "papercut": "/assets/papercut/new-years-eve-papercut-v1.webp",
    "clay": "/assets/clay/new-years-eve-clay-v1.webp",
    "woodblock": "/assets/woodblock/new-years-eve-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/new-years-eve-embroidery-v1.webp"
  },
  "qingming-festival": {
    "minimal": "/assets/minimal/qingming-festival-minimal-v1.webp",
    "character": "/assets/character/qingming-festival-character-v1.webp",
    "anime": "/assets/anime/qingming-festival-anime-v1.webp",
    "sweet": "/assets/sweet/qingming-festival-sweet-v1.webp",
    "watercolor": "/assets/watercolor/qingming-festival-watercolor-v1.webp",
    "papercut": "/assets/papercut/qingming-festival-papercut-v1.webp",
    "clay": "/assets/clay/qingming-festival-clay-v1.webp",
    "woodblock": "/assets/woodblock/qingming-festival-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/qingming-festival-embroidery-v1.webp"
  },
  "qixi": {
    "minimal": "/assets/minimal/qixi-minimal-v1.webp",
    "character": "/assets/character/qixi-character-v1.webp",
    "anime": "/assets/anime/qixi-anime-v1.webp",
    "sweet": "/assets/sweet/qixi-sweet-v1.webp",
    "watercolor": "/assets/watercolor/qixi-watercolor-v1.webp",
    "papercut": "/assets/papercut/qixi-papercut-v1.webp",
    "clay": "/assets/clay/qixi-clay-v1.webp",
    "woodblock": "/assets/woodblock/qixi-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/qixi-embroidery-v1.webp"
  },
  "spring-festival": {
    "minimal": "/assets/minimal/spring-festival-minimal-v1.webp",
    "character": "/assets/character/spring-festival-character-v1.webp",
    "anime": "/assets/anime/spring-festival-anime-v1.webp",
    "sweet": "/assets/sweet/spring-festival-sweet-v1.webp",
    "watercolor": "/assets/watercolor/spring-festival-watercolor-v1.webp",
    "papercut": "/assets/papercut/spring-festival-papercut-v1.webp",
    "clay": "/assets/clay/spring-festival-clay-v1.webp",
    "woodblock": "/assets/woodblock/spring-festival-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/spring-festival-embroidery-v1.webp"
  },
  "teachers-day": {
    "minimal": "/assets/minimal/teachers-day-minimal-v1.webp",
    "character": "/assets/character/teachers-day-character-v1.webp",
    "anime": "/assets/anime/teachers-day-anime-v1.webp",
    "sweet": "/assets/sweet/teachers-day-sweet-v1.webp",
    "watercolor": "/assets/watercolor/teachers-day-watercolor-v1.webp",
    "papercut": "/assets/papercut/teachers-day-papercut-v1.webp",
    "clay": "/assets/clay/teachers-day-clay-v1.webp",
    "woodblock": "/assets/woodblock/teachers-day-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/teachers-day-embroidery-v1.webp"
  },
  "term-bailu": {
    "minimal": "/assets/minimal/bailu-minimal.webp",
    "character": "/assets/character/bailu-character.webp",
    "anime": "/assets/anime/bailu-anime.webp",
    "sweet": "/assets/sweet/bailu-sweet.webp",
    "watercolor": "/assets/watercolor/bailu-watercolor.webp",
    "papercut": "/assets/papercut/bailu-papercut.webp",
    "clay": "/assets/clay/bailu-clay.webp",
    "woodblock": "/assets/woodblock/bailu-woodblock.webp",
    "embroidery": "/assets/embroidery/bailu-embroidery.webp"
  },
  "term-chunfen": {
    "minimal": "/assets/minimal/term-chunfen-minimal-v1.webp",
    "character": "/assets/character/term-chunfen-character-v1.webp",
    "anime": "/assets/anime/term-chunfen-anime-v1.webp",
    "sweet": "/assets/sweet/term-chunfen-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-chunfen-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-chunfen-papercut-v1.webp",
    "clay": "/assets/clay/term-chunfen-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-chunfen-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-chunfen-embroidery-v1.webp"
  },
  "term-chushu": {
    "minimal": "/assets/minimal/term-chushu-minimal-v1.webp",
    "character": "/assets/character/term-chushu-character-v1.webp",
    "anime": "/assets/anime/term-chushu-anime-v1.webp",
    "sweet": "/assets/sweet/term-chushu-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-chushu-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-chushu-papercut-v1.webp",
    "clay": "/assets/clay/term-chushu-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-chushu-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-chushu-embroidery-v1.webp"
  },
  "term-dahan": {
    "minimal": "/assets/minimal/term-dahan-minimal-v1.webp",
    "character": "/assets/character/term-dahan-character-v1.webp",
    "anime": "/assets/anime/term-dahan-anime-v1.webp",
    "sweet": "/assets/sweet/term-dahan-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-dahan-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-dahan-papercut-v1.webp",
    "clay": "/assets/clay/term-dahan-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-dahan-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-dahan-embroidery-v1.webp"
  },
  "term-dashu": {
    "minimal": "/assets/minimal/term-dashu-minimal-v1.webp",
    "character": "/assets/character/term-dashu-character-v1.webp",
    "anime": "/assets/anime/term-dashu-anime-v1.webp",
    "sweet": "/assets/sweet/term-dashu-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-dashu-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-dashu-papercut-v1.webp",
    "clay": "/assets/clay/term-dashu-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-dashu-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-dashu-embroidery-v1.webp"
  },
  "term-daxue": {
    "minimal": "/assets/minimal/term-daxue-minimal-v1.webp",
    "character": "/assets/character/term-daxue-character-v1.webp",
    "anime": "/assets/anime/term-daxue-anime-v1.webp",
    "sweet": "/assets/sweet/term-daxue-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-daxue-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-daxue-papercut-v1.webp",
    "clay": "/assets/clay/term-daxue-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-daxue-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-daxue-embroidery-v1.webp"
  },
  "term-dongzhi": {
    "minimal": "/assets/minimal/term-dongzhi-minimal-v1.webp",
    "character": "/assets/character/term-dongzhi-character-v1.webp",
    "anime": "/assets/anime/term-dongzhi-anime-v1.webp",
    "sweet": "/assets/sweet/term-dongzhi-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-dongzhi-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-dongzhi-papercut-v1.webp",
    "clay": "/assets/clay/term-dongzhi-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-dongzhi-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-dongzhi-embroidery-v1.webp"
  },
  "term-guyu": {
    "minimal": "/assets/minimal/term-guyu-minimal-v1.webp",
    "character": "/assets/character/term-guyu-character-v1.webp",
    "anime": "/assets/anime/term-guyu-anime-v1.webp",
    "sweet": "/assets/sweet/term-guyu-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-guyu-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-guyu-papercut-v1.webp",
    "clay": "/assets/clay/term-guyu-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-guyu-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-guyu-embroidery-v2.webp"
  },
  "term-hanlu": {
    "minimal": "/assets/minimal/term-hanlu-minimal-v1.webp",
    "character": "/assets/character/term-hanlu-character-v1.webp",
    "anime": "/assets/anime/term-hanlu-anime-v1.webp",
    "sweet": "/assets/sweet/term-hanlu-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-hanlu-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-hanlu-papercut-v1.webp",
    "clay": "/assets/clay/term-hanlu-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-hanlu-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-hanlu-embroidery-v1.webp"
  },
  "term-jingzhe": {
    "minimal": "/assets/minimal/term-jingzhe-minimal-v1.webp",
    "character": "/assets/character/term-jingzhe-character-v1.webp",
    "anime": "/assets/anime/term-jingzhe-anime-v1.webp",
    "sweet": "/assets/sweet/term-jingzhe-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-jingzhe-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-jingzhe-papercut-v1.webp",
    "clay": "/assets/clay/term-jingzhe-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-jingzhe-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-jingzhe-embroidery-v1.webp"
  },
  "term-lichun": {
    "minimal": "/assets/minimal/term-lichun-minimal-v1.webp",
    "character": "/assets/character/term-lichun-character-v1.webp",
    "anime": "/assets/anime/term-lichun-anime-v1.webp",
    "sweet": "/assets/sweet/term-lichun-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-lichun-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-lichun-papercut-v1.webp",
    "clay": "/assets/clay/term-lichun-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-lichun-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-lichun-embroidery-v1.webp"
  },
  "term-lidong": {
    "minimal": "/assets/minimal/term-lidong-minimal-v1.webp",
    "character": "/assets/character/term-lidong-character-v1.webp",
    "anime": "/assets/anime/term-lidong-anime-v1.webp",
    "sweet": "/assets/sweet/term-lidong-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-lidong-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-lidong-papercut-v1.webp",
    "clay": "/assets/clay/term-lidong-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-lidong-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-lidong-embroidery-v1.webp"
  },
  "term-liqiu": {
    "minimal": "/assets/minimal/term-liqiu-minimal-v1.webp",
    "character": "/assets/character/term-liqiu-character-v1.webp",
    "anime": "/assets/anime/term-liqiu-anime-v1.webp",
    "sweet": "/assets/sweet/term-liqiu-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-liqiu-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-liqiu-papercut-v1.webp",
    "clay": "/assets/clay/term-liqiu-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-liqiu-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-liqiu-embroidery-v1.webp"
  },
  "term-lixia": {
    "minimal": "/assets/minimal/term-lixia-minimal-v1.webp",
    "character": "/assets/character/term-lixia-character-v1.webp",
    "anime": "/assets/anime/term-lixia-anime-v1.webp",
    "sweet": "/assets/sweet/term-lixia-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-lixia-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-lixia-papercut-v1.webp",
    "clay": "/assets/clay/term-lixia-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-lixia-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-lixia-embroidery-v1.webp"
  },
  "term-mangzhong": {
    "minimal": "/assets/minimal/term-mangzhong-minimal-v1.webp",
    "character": "/assets/character/term-mangzhong-character-v1.webp",
    "anime": "/assets/anime/term-mangzhong-anime-v1.webp",
    "sweet": "/assets/sweet/term-mangzhong-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-mangzhong-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-mangzhong-papercut-v1.webp",
    "clay": "/assets/clay/term-mangzhong-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-mangzhong-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-mangzhong-embroidery-v1.webp"
  },
  "term-qingming": {
    "minimal": "/assets/minimal/term-qingming-minimal-v1.webp",
    "character": "/assets/character/term-qingming-character-v1.webp",
    "anime": "/assets/anime/term-qingming-anime-v1.webp",
    "sweet": "/assets/sweet/term-qingming-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-qingming-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-qingming-papercut-v1.webp",
    "clay": "/assets/clay/term-qingming-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-qingming-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-qingming-embroidery-v1.webp"
  },
  "term-qiufen": {
    "minimal": "/assets/minimal/term-qiufen-minimal-v1.webp",
    "character": "/assets/character/term-qiufen-character-v1.webp",
    "anime": "/assets/anime/term-qiufen-anime-v1.webp",
    "sweet": "/assets/sweet/term-qiufen-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-qiufen-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-qiufen-papercut-v1.webp",
    "clay": "/assets/clay/term-qiufen-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-qiufen-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-qiufen-embroidery-v1.webp"
  },
  "term-shuangjiang": {
    "minimal": "/assets/minimal/term-shuangjiang-minimal-v1.webp",
    "character": "/assets/character/term-shuangjiang-character-v1.webp",
    "anime": "/assets/anime/term-shuangjiang-anime-v1.webp",
    "sweet": "/assets/sweet/term-shuangjiang-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-shuangjiang-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-shuangjiang-papercut-v1.webp",
    "clay": "/assets/clay/term-shuangjiang-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-shuangjiang-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-shuangjiang-embroidery-v1.webp"
  },
  "term-xiaohan": {
    "minimal": "/assets/minimal/term-xiaohan-minimal-v1.webp",
    "character": "/assets/character/term-xiaohan-character-v1.webp",
    "anime": "/assets/anime/term-xiaohan-anime-v1.webp",
    "sweet": "/assets/sweet/term-xiaohan-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-xiaohan-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-xiaohan-papercut-v1.webp",
    "clay": "/assets/clay/term-xiaohan-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-xiaohan-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-xiaohan-embroidery-v1.webp"
  },
  "term-xiaoman": {
    "minimal": "/assets/minimal/term-xiaoman-minimal-v1.webp",
    "character": "/assets/character/term-xiaoman-character-v1.webp",
    "anime": "/assets/anime/term-xiaoman-anime-v1.webp",
    "sweet": "/assets/sweet/term-xiaoman-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-xiaoman-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-xiaoman-papercut-v1.webp",
    "clay": "/assets/clay/term-xiaoman-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-xiaoman-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-xiaoman-embroidery-v1.webp"
  },
  "term-xiaoshu": {
    "minimal": "/assets/minimal/term-xiaoshu-minimal-v1.webp",
    "character": "/assets/character/term-xiaoshu-character-v1.webp",
    "anime": "/assets/anime/term-xiaoshu-anime-v1.webp",
    "sweet": "/assets/sweet/term-xiaoshu-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-xiaoshu-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-xiaoshu-papercut-v1.webp",
    "clay": "/assets/clay/term-xiaoshu-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-xiaoshu-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-xiaoshu-embroidery-v1.webp"
  },
  "term-xiaoxue": {
    "minimal": "/assets/minimal/term-xiaoxue-minimal-v1.webp",
    "character": "/assets/character/term-xiaoxue-character-v1.webp",
    "anime": "/assets/anime/term-xiaoxue-anime-v1.webp",
    "sweet": "/assets/sweet/term-xiaoxue-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-xiaoxue-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-xiaoxue-papercut-v1.webp",
    "clay": "/assets/clay/term-xiaoxue-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-xiaoxue-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-xiaoxue-embroidery-v1.webp"
  },
  "term-xiazhi": {
    "minimal": "/assets/minimal/term-xiazhi-minimal-v1.webp",
    "character": "/assets/character/term-xiazhi-character-v1.webp",
    "anime": "/assets/anime/term-xiazhi-anime-v1.webp",
    "sweet": "/assets/sweet/term-xiazhi-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-xiazhi-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-xiazhi-papercut-v1.webp",
    "clay": "/assets/clay/term-xiazhi-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-xiazhi-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-xiazhi-embroidery-v1.webp"
  },
  "term-yushui": {
    "minimal": "/assets/minimal/term-yushui-minimal-v1.webp",
    "character": "/assets/character/term-yushui-character-v1.webp",
    "anime": "/assets/anime/term-yushui-anime-v1.webp",
    "sweet": "/assets/sweet/term-yushui-sweet-v1.webp",
    "watercolor": "/assets/watercolor/term-yushui-watercolor-v1.webp",
    "papercut": "/assets/papercut/term-yushui-papercut-v1.webp",
    "clay": "/assets/clay/term-yushui-clay-v1.webp",
    "woodblock": "/assets/woodblock/term-yushui-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/term-yushui-embroidery-v1.webp"
  },
  "womens-day": {
    "minimal": "/assets/minimal/womens-day-minimal-v1.webp",
    "character": "/assets/character/womens-day-character-v1.webp",
    "anime": "/assets/anime/womens-day-anime-v1.webp",
    "sweet": "/assets/sweet/womens-day-sweet-v1.webp",
    "watercolor": "/assets/watercolor/womens-day-watercolor-v1.webp",
    "papercut": "/assets/papercut/womens-day-papercut-v1.webp",
    "clay": "/assets/clay/womens-day-clay-v1.webp",
    "woodblock": "/assets/woodblock/womens-day-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/womens-day-embroidery-v1.webp"
  },
  "youth-day": {
    "minimal": "/assets/minimal/youth-day-minimal-v1.webp",
    "character": "/assets/character/youth-day-character-v1.webp",
    "anime": "/assets/anime/youth-day-anime-v1.webp",
    "sweet": "/assets/sweet/youth-day-sweet-v1.webp",
    "watercolor": "/assets/watercolor/youth-day-watercolor-v1.webp",
    "papercut": "/assets/papercut/youth-day-papercut-v1.webp",
    "clay": "/assets/clay/youth-day-clay-v1.webp",
    "woodblock": "/assets/woodblock/youth-day-woodblock-v1.webp",
    "embroidery": "/assets/embroidery/youth-day-embroidery-v1.webp"
  }
};
