// Generated from artwork progress manifests by sync-site or sync-styles. Do not edit.
export const seriesEventIds = [
  "childrens-day",
  "double-ninth",
  "dragon-boat",
  "laba",
  "labour-day",
  "lantern-festival",
  "mid-autumn",
  "national-day",
  "new-year",
  "new-years-eve",
  "qingming-festival",
  "qixi",
  "spring-festival",
  "teachers-day",
  "term-bailu",
  "term-chunfen",
  "term-chushu",
  "term-dahan",
  "term-dashu",
  "term-daxue",
  "term-dongzhi",
  "term-guyu",
  "term-hanlu",
  "term-jingzhe",
  "term-lichun",
  "term-lidong",
  "term-liqiu",
  "term-lixia",
  "term-mangzhong",
  "term-qingming",
  "term-qiufen",
  "term-shuangjiang",
  "term-xiaohan",
  "term-xiaoman",
  "term-xiaoshu",
  "term-xiaoxue",
  "term-xiazhi",
  "term-yushui",
  "womens-day",
  "youth-day"
] as const;
export const seriesArtwork: Record<string, Record<string, string>> = {
  "childrens-day": {
    "minimal": "/assets/childrens-day-minimal-v1.webp",
    "character": "/assets/childrens-day-character-v1.webp",
    "anime": "/assets/childrens-day-anime-v1.webp",
    "sweet": "/assets/childrens-day-sweet-v1.webp",
    "watercolor": "/assets/childrens-day-watercolor-v1.webp",
    "papercut": "/assets/childrens-day-papercut-v1.webp",
    "clay": "/assets/childrens-day-clay-v1.webp",
    "woodblock": "/assets/childrens-day-woodblock-v1.webp",
    "embroidery": "/assets/childrens-day-embroidery-v1.webp"
  },
  "double-ninth": {
    "minimal": "/assets/double-ninth-minimal-v1.webp",
    "character": "/assets/double-ninth-character-v1.webp",
    "anime": "/assets/double-ninth-anime-v1.webp",
    "sweet": "/assets/double-ninth-sweet-v1.webp",
    "watercolor": "/assets/double-ninth-watercolor-v1.webp",
    "papercut": "/assets/double-ninth-papercut-v1.webp",
    "clay": "/assets/double-ninth-clay-v1.webp",
    "woodblock": "/assets/double-ninth-woodblock-v1.webp",
    "embroidery": "/assets/double-ninth-embroidery-v1.webp"
  },
  "dragon-boat": {
    "minimal": "/assets/dragon-boat-minimal-v1.webp",
    "character": "/assets/dragon-boat-character-v1.webp",
    "anime": "/assets/dragon-boat-anime-v1.webp",
    "sweet": "/assets/dragon-boat-sweet-v1.webp",
    "watercolor": "/assets/dragon-boat-watercolor-v1.webp",
    "papercut": "/assets/dragon-boat-papercut-v1.webp",
    "clay": "/assets/dragon-boat-clay-v1.webp",
    "woodblock": "/assets/dragon-boat-woodblock-v1.webp",
    "embroidery": "/assets/dragon-boat-embroidery-v1.webp"
  },
  "laba": {
    "minimal": "/assets/laba-minimal-v1.webp",
    "character": "/assets/laba-character-v1.webp",
    "anime": "/assets/laba-anime-v1.webp",
    "sweet": "/assets/laba-sweet-v1.webp",
    "watercolor": "/assets/laba-watercolor-v1.webp",
    "papercut": "/assets/laba-papercut-v1.webp",
    "clay": "/assets/laba-clay-v1.webp",
    "woodblock": "/assets/laba-woodblock-v1.webp",
    "embroidery": "/assets/laba-embroidery-v1.webp"
  },
  "labour-day": {
    "minimal": "/assets/labour-day-minimal-v1.webp",
    "character": "/assets/labour-day-character-v1.webp",
    "anime": "/assets/labour-day-anime-v1.webp",
    "sweet": "/assets/labour-day-sweet-v1.webp",
    "watercolor": "/assets/labour-day-watercolor-v1.webp",
    "papercut": "/assets/labour-day-papercut-v1.webp",
    "clay": "/assets/labour-day-clay-v1.webp",
    "woodblock": "/assets/labour-day-woodblock-v1.webp",
    "embroidery": "/assets/labour-day-embroidery-v1.webp"
  },
  "lantern-festival": {
    "minimal": "/assets/lantern-festival-minimal-v1.webp",
    "character": "/assets/lantern-festival-character-v1.webp",
    "anime": "/assets/lantern-festival-anime-v1.webp",
    "sweet": "/assets/lantern-festival-sweet-v1.webp",
    "watercolor": "/assets/lantern-festival-watercolor-v1.webp",
    "papercut": "/assets/lantern-festival-papercut-v1.webp",
    "clay": "/assets/lantern-festival-clay-v1.webp",
    "woodblock": "/assets/lantern-festival-woodblock-v1.webp",
    "embroidery": "/assets/lantern-festival-embroidery-v1.webp"
  },
  "mid-autumn": {
    "minimal": "/assets/mid-autumn-minimal-v1.webp",
    "character": "/assets/mid-autumn-character-v1.webp",
    "anime": "/assets/mid-autumn-anime-v1.webp",
    "sweet": "/assets/mid-autumn-sweet-v1.webp",
    "watercolor": "/assets/mid-autumn-watercolor-v1.webp",
    "papercut": "/assets/mid-autumn-papercut-v1.webp",
    "clay": "/assets/mid-autumn-clay-v1.webp",
    "woodblock": "/assets/mid-autumn-woodblock-v1.webp",
    "embroidery": "/assets/mid-autumn-embroidery-v1.webp"
  },
  "national-day": {
    "minimal": "/assets/national-day-minimal-v1.webp",
    "character": "/assets/national-day-character-v1.webp",
    "anime": "/assets/national-day-anime-v1.webp",
    "sweet": "/assets/national-day-sweet-v1.webp",
    "watercolor": "/assets/national-day-watercolor-v1.webp",
    "papercut": "/assets/national-day-papercut-v1.webp",
    "clay": "/assets/national-day-clay-v1.webp",
    "woodblock": "/assets/national-day-woodblock-v1.webp",
    "embroidery": "/assets/national-day-embroidery-v1.webp"
  },
  "new-year": {
    "minimal": "/assets/new-year-minimal-v1.webp",
    "character": "/assets/new-year-character-v1.webp",
    "anime": "/assets/new-year-anime-v1.webp",
    "sweet": "/assets/new-year-sweet-v1.webp",
    "watercolor": "/assets/new-year-watercolor-v1.webp",
    "papercut": "/assets/new-year-papercut-v1.webp",
    "clay": "/assets/new-year-clay-v1.webp",
    "woodblock": "/assets/new-year-woodblock-v1.webp",
    "embroidery": "/assets/new-year-embroidery-v1.webp"
  },
  "new-years-eve": {
    "minimal": "/assets/new-years-eve-minimal-v1.webp",
    "character": "/assets/new-years-eve-character-v1.webp",
    "anime": "/assets/new-years-eve-anime-v1.webp",
    "sweet": "/assets/new-years-eve-sweet-v1.webp",
    "watercolor": "/assets/new-years-eve-watercolor-v1.webp",
    "papercut": "/assets/new-years-eve-papercut-v1.webp",
    "clay": "/assets/new-years-eve-clay-v1.webp",
    "woodblock": "/assets/new-years-eve-woodblock-v1.webp",
    "embroidery": "/assets/new-years-eve-embroidery-v1.webp"
  },
  "qingming-festival": {
    "minimal": "/assets/qingming-festival-minimal-v1.webp",
    "character": "/assets/qingming-festival-character-v1.webp",
    "anime": "/assets/qingming-festival-anime-v1.webp",
    "sweet": "/assets/qingming-festival-sweet-v1.webp",
    "watercolor": "/assets/qingming-festival-watercolor-v1.webp",
    "papercut": "/assets/qingming-festival-papercut-v1.webp",
    "clay": "/assets/qingming-festival-clay-v1.webp",
    "woodblock": "/assets/qingming-festival-woodblock-v1.webp",
    "embroidery": "/assets/qingming-festival-embroidery-v1.webp"
  },
  "qixi": {
    "minimal": "/assets/qixi-minimal-v1.webp",
    "character": "/assets/qixi-character-v1.webp",
    "anime": "/assets/qixi-anime-v1.webp",
    "sweet": "/assets/qixi-sweet-v1.webp",
    "watercolor": "/assets/qixi-watercolor-v1.webp",
    "papercut": "/assets/qixi-papercut-v1.webp",
    "clay": "/assets/qixi-clay-v1.webp",
    "woodblock": "/assets/qixi-woodblock-v1.webp",
    "embroidery": "/assets/qixi-embroidery-v1.webp"
  },
  "spring-festival": {
    "minimal": "/assets/spring-festival-minimal-v1.webp",
    "character": "/assets/spring-festival-character-v1.webp",
    "anime": "/assets/spring-festival-anime-v1.webp",
    "sweet": "/assets/spring-festival-sweet-v1.webp",
    "watercolor": "/assets/spring-festival-watercolor-v1.webp",
    "papercut": "/assets/spring-festival-papercut-v1.webp",
    "clay": "/assets/spring-festival-clay-v1.webp",
    "woodblock": "/assets/spring-festival-woodblock-v1.webp",
    "embroidery": "/assets/spring-festival-embroidery-v1.webp"
  },
  "teachers-day": {
    "minimal": "/assets/teachers-day-minimal-v1.webp",
    "character": "/assets/teachers-day-character-v1.webp",
    "anime": "/assets/teachers-day-anime-v1.webp",
    "sweet": "/assets/teachers-day-sweet-v1.webp",
    "watercolor": "/assets/teachers-day-watercolor-v1.webp",
    "papercut": "/assets/teachers-day-papercut-v1.webp",
    "clay": "/assets/teachers-day-clay-v1.webp",
    "woodblock": "/assets/teachers-day-woodblock-v1.webp",
    "embroidery": "/assets/teachers-day-embroidery-v1.webp"
  },
  "term-bailu": {
    "minimal": "/assets/bailu-minimal.webp",
    "character": "/assets/bailu-character.webp",
    "anime": "/assets/bailu-anime.webp",
    "sweet": "/assets/bailu-sweet.webp",
    "watercolor": "/assets/bailu-watercolor.webp",
    "papercut": "/assets/bailu-papercut.webp",
    "clay": "/assets/bailu-clay.webp",
    "woodblock": "/assets/bailu-woodblock.webp",
    "embroidery": "/assets/bailu-embroidery.webp"
  },
  "term-chunfen": {
    "minimal": "/assets/term-chunfen-minimal-v1.webp",
    "character": "/assets/term-chunfen-character-v1.webp",
    "anime": "/assets/term-chunfen-anime-v1.webp",
    "sweet": "/assets/term-chunfen-sweet-v1.webp",
    "watercolor": "/assets/term-chunfen-watercolor-v1.webp",
    "papercut": "/assets/term-chunfen-papercut-v1.webp",
    "clay": "/assets/term-chunfen-clay-v1.webp",
    "woodblock": "/assets/term-chunfen-woodblock-v1.webp",
    "embroidery": "/assets/term-chunfen-embroidery-v1.webp"
  },
  "term-chushu": {
    "minimal": "/assets/term-chushu-minimal-v1.webp",
    "character": "/assets/term-chushu-character-v1.webp",
    "anime": "/assets/term-chushu-anime-v1.webp",
    "sweet": "/assets/term-chushu-sweet-v1.webp",
    "watercolor": "/assets/term-chushu-watercolor-v1.webp",
    "papercut": "/assets/term-chushu-papercut-v1.webp",
    "clay": "/assets/term-chushu-clay-v1.webp",
    "woodblock": "/assets/term-chushu-woodblock-v1.webp",
    "embroidery": "/assets/term-chushu-embroidery-v1.webp"
  },
  "term-dahan": {
    "minimal": "/assets/term-dahan-minimal-v1.webp",
    "character": "/assets/term-dahan-character-v1.webp",
    "anime": "/assets/term-dahan-anime-v1.webp",
    "sweet": "/assets/term-dahan-sweet-v1.webp",
    "watercolor": "/assets/term-dahan-watercolor-v1.webp",
    "papercut": "/assets/term-dahan-papercut-v1.webp",
    "clay": "/assets/term-dahan-clay-v1.webp",
    "woodblock": "/assets/term-dahan-woodblock-v1.webp",
    "embroidery": "/assets/term-dahan-embroidery-v1.webp"
  },
  "term-dashu": {
    "minimal": "/assets/term-dashu-minimal-v1.webp",
    "character": "/assets/term-dashu-character-v1.webp",
    "anime": "/assets/term-dashu-anime-v1.webp",
    "sweet": "/assets/term-dashu-sweet-v1.webp",
    "watercolor": "/assets/term-dashu-watercolor-v1.webp",
    "papercut": "/assets/term-dashu-papercut-v1.webp",
    "clay": "/assets/term-dashu-clay-v1.webp",
    "woodblock": "/assets/term-dashu-woodblock-v1.webp",
    "embroidery": "/assets/term-dashu-embroidery-v1.webp"
  },
  "term-daxue": {
    "minimal": "/assets/term-daxue-minimal-v1.webp",
    "character": "/assets/term-daxue-character-v1.webp",
    "anime": "/assets/term-daxue-anime-v1.webp",
    "sweet": "/assets/term-daxue-sweet-v1.webp",
    "watercolor": "/assets/term-daxue-watercolor-v1.webp",
    "papercut": "/assets/term-daxue-papercut-v1.webp",
    "clay": "/assets/term-daxue-clay-v1.webp",
    "woodblock": "/assets/term-daxue-woodblock-v1.webp",
    "embroidery": "/assets/term-daxue-embroidery-v1.webp"
  },
  "term-dongzhi": {
    "minimal": "/assets/term-dongzhi-minimal-v1.webp",
    "character": "/assets/term-dongzhi-character-v1.webp",
    "anime": "/assets/term-dongzhi-anime-v1.webp",
    "sweet": "/assets/term-dongzhi-sweet-v1.webp",
    "watercolor": "/assets/term-dongzhi-watercolor-v1.webp",
    "papercut": "/assets/term-dongzhi-papercut-v1.webp",
    "clay": "/assets/term-dongzhi-clay-v1.webp",
    "woodblock": "/assets/term-dongzhi-woodblock-v1.webp",
    "embroidery": "/assets/term-dongzhi-embroidery-v1.webp"
  },
  "term-guyu": {
    "minimal": "/assets/term-guyu-minimal-v1.webp",
    "character": "/assets/term-guyu-character-v1.webp",
    "anime": "/assets/term-guyu-anime-v1.webp",
    "sweet": "/assets/term-guyu-sweet-v1.webp",
    "watercolor": "/assets/term-guyu-watercolor-v1.webp",
    "papercut": "/assets/term-guyu-papercut-v1.webp",
    "clay": "/assets/term-guyu-clay-v1.webp",
    "woodblock": "/assets/term-guyu-woodblock-v1.webp",
    "embroidery": "/assets/term-guyu-embroidery-v1.webp"
  },
  "term-hanlu": {
    "minimal": "/assets/term-hanlu-minimal-v1.webp",
    "character": "/assets/term-hanlu-character-v1.webp",
    "anime": "/assets/term-hanlu-anime-v1.webp",
    "sweet": "/assets/term-hanlu-sweet-v1.webp",
    "watercolor": "/assets/term-hanlu-watercolor-v1.webp",
    "papercut": "/assets/term-hanlu-papercut-v1.webp",
    "clay": "/assets/term-hanlu-clay-v1.webp",
    "woodblock": "/assets/term-hanlu-woodblock-v1.webp",
    "embroidery": "/assets/term-hanlu-embroidery-v1.webp"
  },
  "term-jingzhe": {
    "minimal": "/assets/term-jingzhe-minimal-v1.webp",
    "character": "/assets/term-jingzhe-character-v1.webp",
    "anime": "/assets/term-jingzhe-anime-v1.webp",
    "sweet": "/assets/term-jingzhe-sweet-v1.webp",
    "watercolor": "/assets/term-jingzhe-watercolor-v1.webp",
    "papercut": "/assets/term-jingzhe-papercut-v1.webp",
    "clay": "/assets/term-jingzhe-clay-v1.webp",
    "woodblock": "/assets/term-jingzhe-woodblock-v1.webp",
    "embroidery": "/assets/term-jingzhe-embroidery-v1.webp"
  },
  "term-lichun": {
    "minimal": "/assets/term-lichun-minimal-v1.webp",
    "character": "/assets/term-lichun-character-v1.webp",
    "anime": "/assets/term-lichun-anime-v1.webp",
    "sweet": "/assets/term-lichun-sweet-v1.webp",
    "watercolor": "/assets/term-lichun-watercolor-v1.webp",
    "papercut": "/assets/term-lichun-papercut-v1.webp",
    "clay": "/assets/term-lichun-clay-v1.webp",
    "woodblock": "/assets/term-lichun-woodblock-v1.webp",
    "embroidery": "/assets/term-lichun-embroidery-v1.webp"
  },
  "term-lidong": {
    "minimal": "/assets/term-lidong-minimal-v1.webp",
    "character": "/assets/term-lidong-character-v1.webp",
    "anime": "/assets/term-lidong-anime-v1.webp",
    "sweet": "/assets/term-lidong-sweet-v1.webp",
    "watercolor": "/assets/term-lidong-watercolor-v1.webp",
    "papercut": "/assets/term-lidong-papercut-v1.webp",
    "clay": "/assets/term-lidong-clay-v1.webp",
    "woodblock": "/assets/term-lidong-woodblock-v1.webp",
    "embroidery": "/assets/term-lidong-embroidery-v1.webp"
  },
  "term-liqiu": {
    "minimal": "/assets/term-liqiu-minimal-v1.webp",
    "character": "/assets/term-liqiu-character-v1.webp",
    "anime": "/assets/term-liqiu-anime-v1.webp",
    "sweet": "/assets/term-liqiu-sweet-v1.webp",
    "watercolor": "/assets/term-liqiu-watercolor-v1.webp",
    "papercut": "/assets/term-liqiu-papercut-v1.webp",
    "clay": "/assets/term-liqiu-clay-v1.webp",
    "woodblock": "/assets/term-liqiu-woodblock-v1.webp",
    "embroidery": "/assets/term-liqiu-embroidery-v1.webp"
  },
  "term-lixia": {
    "minimal": "/assets/term-lixia-minimal-v1.webp",
    "character": "/assets/term-lixia-character-v1.webp",
    "anime": "/assets/term-lixia-anime-v1.webp",
    "sweet": "/assets/term-lixia-sweet-v1.webp",
    "watercolor": "/assets/term-lixia-watercolor-v1.webp",
    "papercut": "/assets/term-lixia-papercut-v1.webp",
    "clay": "/assets/term-lixia-clay-v1.webp",
    "woodblock": "/assets/term-lixia-woodblock-v1.webp",
    "embroidery": "/assets/term-lixia-embroidery-v1.webp"
  },
  "term-mangzhong": {
    "minimal": "/assets/term-mangzhong-minimal-v1.webp",
    "character": "/assets/term-mangzhong-character-v1.webp",
    "anime": "/assets/term-mangzhong-anime-v1.webp",
    "sweet": "/assets/term-mangzhong-sweet-v1.webp",
    "watercolor": "/assets/term-mangzhong-watercolor-v1.webp",
    "papercut": "/assets/term-mangzhong-papercut-v1.webp",
    "clay": "/assets/term-mangzhong-clay-v1.webp",
    "woodblock": "/assets/term-mangzhong-woodblock-v1.webp",
    "embroidery": "/assets/term-mangzhong-embroidery-v1.webp"
  },
  "term-qingming": {
    "minimal": "/assets/term-qingming-minimal-v1.webp",
    "character": "/assets/term-qingming-character-v1.webp",
    "anime": "/assets/term-qingming-anime-v1.webp",
    "sweet": "/assets/term-qingming-sweet-v1.webp",
    "watercolor": "/assets/term-qingming-watercolor-v1.webp",
    "papercut": "/assets/term-qingming-papercut-v1.webp",
    "clay": "/assets/term-qingming-clay-v1.webp",
    "woodblock": "/assets/term-qingming-woodblock-v1.webp",
    "embroidery": "/assets/term-qingming-embroidery-v1.webp"
  },
  "term-qiufen": {
    "minimal": "/assets/term-qiufen-minimal-v1.webp",
    "character": "/assets/term-qiufen-character-v1.webp",
    "anime": "/assets/term-qiufen-anime-v1.webp",
    "sweet": "/assets/term-qiufen-sweet-v1.webp",
    "watercolor": "/assets/term-qiufen-watercolor-v1.webp",
    "papercut": "/assets/term-qiufen-papercut-v1.webp",
    "clay": "/assets/term-qiufen-clay-v1.webp",
    "woodblock": "/assets/term-qiufen-woodblock-v1.webp",
    "embroidery": "/assets/term-qiufen-embroidery-v1.webp"
  },
  "term-shuangjiang": {
    "minimal": "/assets/term-shuangjiang-minimal-v1.webp",
    "character": "/assets/term-shuangjiang-character-v1.webp",
    "anime": "/assets/term-shuangjiang-anime-v1.webp",
    "sweet": "/assets/term-shuangjiang-sweet-v1.webp",
    "watercolor": "/assets/term-shuangjiang-watercolor-v1.webp",
    "papercut": "/assets/term-shuangjiang-papercut-v1.webp",
    "clay": "/assets/term-shuangjiang-clay-v1.webp",
    "woodblock": "/assets/term-shuangjiang-woodblock-v1.webp",
    "embroidery": "/assets/term-shuangjiang-embroidery-v1.webp"
  },
  "term-xiaohan": {
    "minimal": "/assets/term-xiaohan-minimal-v1.webp",
    "character": "/assets/term-xiaohan-character-v1.webp",
    "anime": "/assets/term-xiaohan-anime-v1.webp",
    "sweet": "/assets/term-xiaohan-sweet-v1.webp",
    "watercolor": "/assets/term-xiaohan-watercolor-v1.webp",
    "papercut": "/assets/term-xiaohan-papercut-v1.webp",
    "clay": "/assets/term-xiaohan-clay-v1.webp",
    "woodblock": "/assets/term-xiaohan-woodblock-v1.webp",
    "embroidery": "/assets/term-xiaohan-embroidery-v1.webp"
  },
  "term-xiaoman": {
    "minimal": "/assets/term-xiaoman-minimal-v1.webp",
    "character": "/assets/term-xiaoman-character-v1.webp",
    "anime": "/assets/term-xiaoman-anime-v1.webp",
    "sweet": "/assets/term-xiaoman-sweet-v1.webp",
    "watercolor": "/assets/term-xiaoman-watercolor-v1.webp",
    "papercut": "/assets/term-xiaoman-papercut-v1.webp",
    "clay": "/assets/term-xiaoman-clay-v1.webp",
    "woodblock": "/assets/term-xiaoman-woodblock-v1.webp",
    "embroidery": "/assets/term-xiaoman-embroidery-v1.webp"
  },
  "term-xiaoshu": {
    "minimal": "/assets/term-xiaoshu-minimal-v1.webp",
    "character": "/assets/term-xiaoshu-character-v1.webp",
    "anime": "/assets/term-xiaoshu-anime-v1.webp",
    "sweet": "/assets/term-xiaoshu-sweet-v1.webp",
    "watercolor": "/assets/term-xiaoshu-watercolor-v1.webp",
    "papercut": "/assets/term-xiaoshu-papercut-v1.webp",
    "clay": "/assets/term-xiaoshu-clay-v1.webp",
    "woodblock": "/assets/term-xiaoshu-woodblock-v1.webp",
    "embroidery": "/assets/term-xiaoshu-embroidery-v1.webp"
  },
  "term-xiaoxue": {
    "minimal": "/assets/term-xiaoxue-minimal-v1.webp",
    "character": "/assets/term-xiaoxue-character-v1.webp",
    "anime": "/assets/term-xiaoxue-anime-v1.webp",
    "sweet": "/assets/term-xiaoxue-sweet-v1.webp",
    "watercolor": "/assets/term-xiaoxue-watercolor-v1.webp",
    "papercut": "/assets/term-xiaoxue-papercut-v1.webp",
    "clay": "/assets/term-xiaoxue-clay-v1.webp",
    "woodblock": "/assets/term-xiaoxue-woodblock-v1.webp",
    "embroidery": "/assets/term-xiaoxue-embroidery-v1.webp"
  },
  "term-xiazhi": {
    "minimal": "/assets/term-xiazhi-minimal-v1.webp",
    "character": "/assets/term-xiazhi-character-v1.webp",
    "anime": "/assets/term-xiazhi-anime-v1.webp",
    "sweet": "/assets/term-xiazhi-sweet-v1.webp",
    "watercolor": "/assets/term-xiazhi-watercolor-v1.webp",
    "papercut": "/assets/term-xiazhi-papercut-v1.webp",
    "clay": "/assets/term-xiazhi-clay-v1.webp",
    "woodblock": "/assets/term-xiazhi-woodblock-v1.webp",
    "embroidery": "/assets/term-xiazhi-embroidery-v1.webp"
  },
  "term-yushui": {
    "minimal": "/assets/term-yushui-minimal-v1.webp",
    "character": "/assets/term-yushui-character-v1.webp",
    "anime": "/assets/term-yushui-anime-v1.webp",
    "sweet": "/assets/term-yushui-sweet-v1.webp",
    "watercolor": "/assets/term-yushui-watercolor-v1.webp",
    "papercut": "/assets/term-yushui-papercut-v1.webp",
    "clay": "/assets/term-yushui-clay-v1.webp",
    "woodblock": "/assets/term-yushui-woodblock-v1.webp",
    "embroidery": "/assets/term-yushui-embroidery-v1.webp"
  },
  "womens-day": {
    "minimal": "/assets/womens-day-minimal-v1.webp",
    "character": "/assets/womens-day-character-v1.webp",
    "anime": "/assets/womens-day-anime-v1.webp",
    "sweet": "/assets/womens-day-sweet-v1.webp",
    "watercolor": "/assets/womens-day-watercolor-v1.webp",
    "papercut": "/assets/womens-day-papercut-v1.webp",
    "clay": "/assets/womens-day-clay-v1.webp",
    "woodblock": "/assets/womens-day-woodblock-v1.webp",
    "embroidery": "/assets/womens-day-embroidery-v1.webp"
  },
  "youth-day": {
    "minimal": "/assets/youth-day-minimal-v1.webp",
    "character": "/assets/youth-day-character-v1.webp",
    "anime": "/assets/youth-day-anime-v1.webp",
    "sweet": "/assets/youth-day-sweet-v1.webp",
    "watercolor": "/assets/youth-day-watercolor-v1.webp",
    "papercut": "/assets/youth-day-papercut-v1.webp",
    "clay": "/assets/youth-day-clay-v1.webp",
    "woodblock": "/assets/youth-day-woodblock-v1.webp",
    "embroidery": "/assets/youth-day-embroidery-v1.webp"
  }
};
